name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.dockerhub@1109 }}" | docker login -u "${{ secrets.ashapendyala }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.ashapendyala }}/my-flask-app:latest .

      - name: Push to Docker Hub
        run: docker push ${{ secrets.ashapendyala }}/my-flask-app:latest
